### ISSUE TITLE
error while using theme

### ISSUE THREAD

**Issue by Dan1jel** [arbourd/prompt#1]
I get errors while using the theme, is this something you could maybe fix or is this a dead projekt?

**Comment by arbourd** [comment]
Hej! Had no idea anyone other than me was using it.

It's not dead but I'm still using it with fish 3.1.2. What's the error / issue?

**Comment by arbourd** [comment]
Ah I see, the owner of `fish-git-util` deleted the repo (and newer fisher doesn't support dependencies). The quick fix for the moment is:

```console
$ fisher install arbourd/fish-git-util
```

**Comment by Dan1jel** [comment]
Just found it, and it looks kind of minimalist, so i was going to give it a try but got a lot of errors instead. Great thanks, will try i your when I have a moment free.

**Comment by arbourd** [comment]
`prompt` has been updated to fix this issue and not require `fish-git-util`. If you're still having problems please let me know 😁
